<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LIHFU2U" failures="1" tests="4" name="Test(failed)(failed)" time="54.238" errors="0" timestamp="2025-01-30T01:22:14 EST">
  <testcase classname="codenbox.testCases.RegistrationTest" name="verify_registration" time="2.035"/>
  <testcase classname="codenbox.testCases.LoginTest" name="verify_login" time="11.349">
    <skipped/>
  </testcase> <!-- verify_login -->
  <testcase classname="codenbox.testCases.LoginTest" name="verify_login" time="11.21">
    <skipped/>
  </testcase> <!-- verify_login -->
  <testcase classname="codenbox.testCases.LoginTest" name="verify_login" time="11.093">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at codenbox.testCases.LoginTest.verify_login(LoginTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_login -->
</testsuite> <!-- Test(failed)(failed) -->
